[config]
schemaVersion = "0.0.1"

[package]
namespace = "GyztorMizirath"
name = "ResoniteInputControl"
versionNumber = "1.0.0"
description = "A Bepis Mod Loader mod (Add more later)."
websiteUrl = "https://github.com/Gyztor/BepisResoniteInputControl"
containsNsfwContent = false

[package.dependencies]
ResoniteModding-BepisLoader = "1.6.0"


[build]
icon = "./Icon.png"
readme = "./README.md"
outdir = "./bin/build"

[[build.copy]]
source = "./license.txt"
target = "/"


[[build.copy]]
source = "./ResoniteInputControl/bin/Release/ResoniteInputControl.dll"
target = "plugins/ResoniteInputControl/"

[[build.copy]]
source = "./ResoniteInputControl/bin/Release/ResoniteInputControl.pdb"
target = "plugins/ResoniteInputControl/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = []

